### ISSUE TITLE
Support for international keyboards?

### ISSUE THREAD

**Issue by tiagoantao** [anmonteiro/snoopy-mode#3]
The current code only supports American keyboards (I am pretty sure that is will not work with other English language keyboards - for example British keyboards are different).

I have myself American keyboards here, so I am not a good guinea-pig to test this.

I suspect a framework for other keyboard configurations would be like a good first step?

**Comment by anmonteiro** [comment]
I'm aware of this, but we may need to do some research in order to support international keyboards.

I always use the American layout, but I do have a Portuguese keyboard that I can test with.

**Comment by AdrieanKhisbe** [comment]
@anmonteiro 

I started working on a prototype, and it's working:
https://github.com/AdrieanKhisbe/snoopy-mode/tree/i18n-support

A diff is viewable there: https://github.com/anmonteiro/snoopy-mode/compare/master...AdrieanKhisbe:i18n-support.
I wait a bit before to make a PR since it's still work in progress

**Comment by anmonteiro** [comment]
That’s awesome. Feel free to PR when you think it’s ready and I’ll test it out and provide feedback

**Comment by AdrieanKhisbe** [comment]
Here it is. 😃 
I have some other ideas in mind, among them enabling to have as keyboard definition just a string: `"&é\"'(§è!çà"` for instance.

But that could wait for after a v0.2

**Comment by AdrieanKhisbe** [comment]
I'm also thinking about putting in place a test infrastructure thanks to https://github.com/AdrieanKhisbe/cask-package-toolset.el

**Comment by anmonteiro** [comment]
Thanks for your interest. Testing would be most welcome

**Comment by AdrieanKhisbe** [comment]
I set up testing infrastructure and a basic test that happen to be covering a lot:
- diff: https://github.com/AdrieanKhisbe/snoopy-mode/compare/i18n-support...AdrieanKhisbe:ci-setup
- travis: https://travis-ci.org/AdrieanKhisbe/snoopy-mode/builds/279160542
- coveralls: https://coveralls.io/github/AdrieanKhisbe/snoopy-mode

Tell me if you prefer to do it in the same PR, or have a dedicated PR

**Comment by anmonteiro** [comment]
Separate PR please

**Comment by AdrieanKhisbe** [comment]
okey dokey

**Comment by AdrieanKhisbe** [comment]
@anmonteiro you can check it out: #6

**Comment by wbolster** [comment]
for inspiration, in evil-swap-keys, i have a defcustom to map the numbers to symbols: https://github.com/wbolster/evil-swap-keys/blob/master/evil-swap-keys.el#L27-L44
